### ISSUE TITLE
Teletext-Zeichensätze korrigieren

### ISSUE THREAD

**Issue by mkraemer0** [OpenPLi/tuxtxt#1]
Auf Wikipedia
(https://de.wikipedia.org/wiki/Teletext-Zeichens%C3%A4tze_%28ETSI_EN_300_706%29)
habe ich eine Übersicht der Teletext-Zeichensätze mit Unicode-Zuordnung
veröffentlicht, die ich vor längerer Zeit erstellt habe.

Diese habe ich jetzt mal mit den Daten in der Datei "https://github.com/OpenPLi/tuxtxt/blob/master/libtuxtxt/tuxtxt_common.h" verglichen, wobei mir dort die folgenden Fehler bzw.
Ungenauigkeiten aufgefallen sind:

Wert in tuxtxt_common.h -> Korrekter Wert

0x0300 -> 0060
0x0301 -> 00B4
0x0303 -> 02DC
0x02C9 -> 00AF
0x2014 -> 2015
0x20AC -> 20A0
0x03B1 -> 221D
0x00D0 -> 0110

0x0300 -> 0060
0x0301 -> 00B4
0x02C9 -> 00AF
0x2014 -> 2015
0x20AC -> 20A0
0x03B1 -> 221D

0x0300 -> 0060
0x0301 -> 00B4
0x02C9 -> 00AF
0x2014 -> 2015
0x20AC -> 20A0
0x03B1 -> 221D

0x0639 -> FEC9
0xFEC9 -> FE81
0xFE89 -> FE8A
0xFB6D -> FB8A
0xFB8E -> FB94
0x25A0 -> 0020

0x05F2 -> 0022
0x2551 -> 2225

0x05F2 -> 0022
0x066A -> 0025
0xFEF0 -> FE73
0xFD3F -> 0029
0xFD3E -> 0028
',' -> 060C
0x0621 -> FE80
0x0628 -> FE8F
0x062A -> FE95
0x0630 -> FEAB
0xFEC1 -> FEC3
0xFEC5 -> FEC7
0xFEEF -> FEF0
0xFEF0 -> FEEF

0x0457 -> 00EF
0x0161 -> 0160
0x0161 -> 0160
0x0162 -> 021A
0x00AD -> 2015
0x0451 -> 00EB
0x015E -> 0218
0x01CD -> 0102
0x01CF -> 00CE
0x0163 -> 021B
0x00D0 -> 0110
0x0451 -> 00EB
0x2551 -> 2225
0x00F3 -> 00F2
0x015F -> 0219
0x01CE -> 0103

**Comment by milosoftware** [comment]
Patch? Pull request?
